services:
  frontend:
    profiles:
      - dev

  nginx:
    volumes:
      - ./nginx/prod:/etc/nginx/conf.d:ro
      - ./frontend/dist:/var/www/frontend:ro
      - metube_storage:/var/www/storage-root:ro
    depends_on:
      - backend
      - reverb
