export const STORAGE_KEYS = {
    WATCH_HISTORY:    'metube:watch-history',
    LIKED_VIDEOS:     'metube:liked-videos',
    DISLIKED_VIDEOS:  'metube:disliked-videos',
    SAVED_VIDEOS:     'metube:saved-videos',
    VIDEO_PROGRESS:   'metube:video-progress',
    AUTOPLAY:         'metube:autoplay',
    PINNED_VIDEO:     'metube:pinned-video',
    SHORTS_MUTED:     'metube:shorts-muted',
    SHORTS_VOLUME:    'metube:shorts-volume',
    THEME_MODE:       'theme-mode',
    THEME_COLOR:      'theme-color',
    LANGUAGE:         'lang',
    RECENT_SEARCHES:  'metube:recent-searches',
    SUBSCRIPTIONS:    'metube:subscriptions',
    PLAYLISTS:        'metube:playlists',
    MOST_VIEWED_LAYOUT: 'metube:most-viewed-layout',
    SIDEBAR_COLLAPSED: 'metube:sidebar-collapsed',
    SIDEBAR_SECTIONS: 'metube:sidebar-sections',
    RECENT_CHANNELS: 'metube:recent-channels',
    THEATER_MODE: 'metube:theater-mode',
    PLAYER_VOLUME: 'metube:player-volume',
    PLAYER_MUTED: 'metube:player-muted',
    PLAYER_RATE: 'metube:player-rate',
    PLAYER_QUALITY: 'metube:player-quality',
    PLAYER_AMBIENT: 'metube:player-ambient',
    CAPTION_SIZE: 'metube:caption-size',
} as const;
