export const STORAGE_KEYS = {
    WATCH_HISTORY:   'vidsum:watch-history',
    LIKED_VIDEOS:    'vidsum:liked-videos',
    DISLIKED_VIDEOS: 'vidsum:disliked-videos',
    SAVED_VIDEOS:    'vidsum:saved-videos',
    VIDEO_PROGRESS:  'vidsum:video-progress',
    AUTOPLAY:        'vidsum:autoplay',
    WATCH_EVENTS:    'vidsum:watch-events',
    PINNED_VIDEO:    'vidsum:pinned-video',
    SHORTS_MUTED:    'vidsum:shorts-muted',
    SHORTS_VOLUME:   'vidsum:shorts-volume',
    THEME_MODE:      'theme-mode',
    THEME_COLOR:     'theme-color',
    LANGUAGE:        'lang',
} as const;
