export const STORAGE_KEYS = {
    WATCH_HISTORY:    'vidsum:watch-history',
    LIKED_VIDEOS:     'vidsum:liked-videos',
    DISLIKED_VIDEOS:  'vidsum:disliked-videos',
    SAVED_VIDEOS:     'vidsum:saved-videos',
    VIDEO_PROGRESS:   'vidsum:video-progress',
    AUTOPLAY:         'vidsum:autoplay',
    PINNED_VIDEO:     'vidsum:pinned-video',
    SHORTS_MUTED:     'vidsum:shorts-muted',
    SHORTS_VOLUME:    'vidsum:shorts-volume',
    THEME_MODE:       'theme-mode',
    THEME_COLOR:      'theme-color',
    LANGUAGE:         'lang',
    RECENT_SEARCHES:  'vidsum:recent-searches',
    SUBSCRIPTIONS:    'vidsum:subscriptions',
    PLAYLISTS:        'vidsum:playlists',
    MOST_VIEWED_LAYOUT: 'vidsum:most-viewed-layout',
} as const;
